### ISSUE TITLE
SMDBA throws wrong error on failure

### ISSUE THREAD

**Issue by sbluhm** [SUSE/smdba#48]
Running `/usr/bin/smdba` with postgresql fails with

```
General error:
	Unknown database backend. Please check /etc/rhn/rhn.conf configuration file.
```

should /etc/sysconfig/postgresql not exist.

A specific exception is not raised in postgresqlgate.py (class PgSQLGate). `GateException` should be raised.

**Comment by sbluhm** [comment]
this was nonsense.

**Comment by sbluhm** [comment]
I see two options here:

1. In `PgSQLGate.__init__` run a `PgSQLGate.check()`.
2. Put a `Try` around the relevant loop in `PgSQLGate._get_sysconfig` and `PgSQLGate._get_pg_data`.

Let me know which one you prefer and I will create the fix.

**Comment by agraul** [comment]
First I would like to mention that I don't fully know the context around SMDBA and the pre-conditions that are expected. But I wand to leave a small comment before I take a deeper look nonetheless.

I think I wouldn't add a `.check()` call into the constructor, `check()` does a lot of things that will make it harder to test `PgSQLGate` (e.g. we'd need to mock `os.popen` everywhere then). I think that checking for the existence of the config file could  be moved from `check()` to `__init__()`. It does not really make sense to me to call `_get_sysconfig` and `_get_pg_data` if the file doesn't exist.

This is all assuming that the file is not optional and we need to fail anyway if the file is missing.

**Comment by sbluhm** [comment]
@agraul , I just created a PR for a different purpose which does a check at __init__. So it would be only two additional lines to complete this.

**Comment by sbluhm** [comment]
Solved.
