### ISSUE TITLE
Make argument "--backup-dir" symlink aware

### ISSUE THREAD

**Issue by wombelix** [SUSE/smdba#51]
Background:
I'm running a SUSE Manager and as part of the 4.2 Migration the decision was made to move `/var/spacewalk/db-backup` to an NFS Share. I'm also use the same share to keep backups of other SUMA files, so I chose `/var/spacewalk/backup` as new mountepoint, created a subfolder `db-backup` and point from `/var/spacewalk/db-backup` to `/var/spacewalk/backup/db-backup` via symlink. 
From a technical point of view all good, but I had to learn that smdba is checking the Owner / Permissions on the db-backup folder and that they are supposed to be similar to `/var/lib/pgsql/data`. The actual folder `/var/spacewalk/backup/db-backup` has the same permissions, but the symlink `/var/spacewalk/db-backup` has 777, which can't be changed on Linux (only MacOS and *BSD via '-h' argument of chmod).

Suggestion:
Allow to skip the Permission Check so that smdba can be used to create Database Backups even in a Environment with e.g. symlinks. It could be a cli parameter and the default behavior shouldn't be changed, if it's not set, the Permission check should be done as before.

Quick & Dirty Hack (not really an elegant solution)
```
/usr/lib/python3.6/site-packages/smdba# diff -u postgresqlgate.py_org postgresqlgate.py
--- postgresqlgate.py_org       2021-08-27 17:10:22.780052665 +0200
+++ postgresqlgate.py   2021-08-27 17:00:39.018932136 +0200
@@ -771,9 +771,10 @@
                                         "same user and group as \"%s\" directory."
                                         % (args['backup-dir'], self.config['pcnf_pg_data']))
                 # Same permissions?
-                if oct(os.lstat(args['backup-dir']).st_mode & 0o777) != oct(os.lstat(self.config['pcnf_pg_data']).st_mode & 0o777):
-                    raise GateException("The \"%s\" directory must have the same permissions as \"%s\" directory."
-                                        % (args['backup-dir'], self.config['pcnf_pg_data']))
+                if 'checkperm' not in args.keys() or args.get('checkperm') == 'true':
+                    if oct(os.lstat(args['backup-dir']).st_mode & 0o777) != oct(os.lstat(self.config['pcnf_pg_data']).st_mode & 0o777):
+                        raise GateException("The \"%s\" directory must have the same permissions as \"%s\" directory."
+                                            % (args['backup-dir'], self.config['pcnf_pg_data']))
             self._perform_enable_backups(**args)

         if 'source' in args.keys():
```
I've just used a new CLI argument `checkperm` so I can skip the Permission check e.g. with `--checkperm=false`.
Was fine for me to quickly get the backup running again, Owner Check wasn't a problem because `chown -h postgres:postgres /var/spacewalk/db-backup ` could be used to change the owner of the symlink from root to postgres.

Let me know what you think about and what's the best approach to implement it, skipping Owner and Permission check might be better and make it easier to use. Would be great if I don't have to apply my hack with every SUMA Upgrade in Future and to see something like that as part of the official package.

Cheers
Dominik

**Comment by wombelix** [comment]
I realized this morning that there might be some confusion about my request, due to the fact that i could also just use a different Path for the `--backup-dir` argument, also my workaround from yesterday felt really hacky...

So why not use a different Path? To stay aligned with the SUSE Manager Documentation: https://documentation.suse.com/suma/4.2/en/suse-manager/administration/backup-restore.html#_perform_a_manual_database_backup
It doesn't matter how good internal documentation is, vendor Documentation might always "overrule", means if the Admin of a SUMA Instance change, and for example due to an incident an urgent restore is required, the chances are higher the new guy will look for the backup path SUSE is suggesting in the official docs instead internal resources.

Also I changed my proposal / workaround to cover two scenarios:
1) If the given path of backup-dir is a symlink, that value will be overwritten by the actual target, so the owner/permission on the symlink are not relevant anymore, but it's expected that the target is configured identical as /var/lib/pgsql/data
2) To completely disable the Owner / Permission check, you can add the argument `--checkperm=off`

```
--- /usr/lib/python3.6/site-packages/smdba/postgresqlgate.py_org        2021-08-27 17:10:22.780052665 +0200
+++ /usr/lib/python3.6/site-packages/smdba/postgresqlgate.py    2021-08-28 09:15:08.316261204 +0200
@@ -764,16 +764,20 @@
         if 'enable' in args.keys():
             # Check destination only in case user is enabling the backup
            if args.get('enable') == 'on':
-                # Same owner?
-                if os.lstat(args['backup-dir']).st_uid != os.lstat(self.config['pcnf_pg_data']).st_uid \
-                       or os.lstat(args['backup-dir']).st_gid != os.lstat(self.config['pcnf_pg_data']).st_gid:
-                    raise GateException("The \"%s\" directory must belong to the "
-                                        "same user and group as \"%s\" directory."
-                                        % (args['backup-dir'], self.config['pcnf_pg_data']))
-                # Same permissions?
-                if oct(os.lstat(args['backup-dir']).st_mode & 0o777) != oct(os.lstat(self.config['pcnf_pg_data']).st_mode & 0o777):
-                    raise GateException("The \"%s\" directory must have the same permissions as \"%s\" directory."
-                                        % (args['backup-dir'], self.config['pcnf_pg_data']))
+                # If backup-dir is Symlink, use target instead
+                if os.path.islink(args['backup-dir']):
+                    args['backup-dir'] = os.readlink(args['backup-dir'])
+                if args.get('checkperm') != 'off':
+                    # Same owner?
+                    if os.lstat(args['backup-dir']).st_uid != os.lstat(self.config['pcnf_pg_data']).st_uid \
+                           or os.lstat(args['backup-dir']).st_gid != os.lstat(self.config['pcnf_pg_data']).st_gid:
+                        raise GateException("The \"%s\" directory must belong to the "
+                                            "same user and group as \"%s\" directory."
+                                            % (args['backup-dir'], self.config['pcnf_pg_data']))
+                    # Same permissions?
+                    if oct(os.lstat(args['backup-dir']).st_mode & 0o777) != oct(os.lstat(self.config['pcnf_pg_data']).st_mode & 0o777):
+                        raise GateException("The \"%s\" directory must have the same permissions as \"%s\" directory."
+                                            % (args['backup-dir'], self.config['pcnf_pg_data']))
             self._perform_enable_backups(**args)

         if 'source' in args.keys():
```

Cheers
Dominik

**Comment by vzhestkov** [comment]
@wombelix 
Why not to do it this way:
```
--- a/src/smdba/postgresqlgate.py
+++ b/src/smdba/postgresqlgate.py
@@ -767,6 +767,9 @@ class PgSQLGate(BaseGate):
         if 'enable' in args.keys():
             # Check destination only in case user is enabling the backup
             if args.get('enable') == 'on':
+                # If backup-dir is Symlink, use target instead
+                while os.path.islink(args['backup-dir']):
+                    args['backup-dir'] = os.readlink(args['backup-dir'])
                 # Same owner?
                 if os.lstat(args['backup-dir']).st_uid != os.lstat(self.config['pcnf_pg_data']).st_uid \
                        or os.lstat(args['backup-dir']).st_gid != os.lstat(self.config['pcnf_pg_data']).st_gid:
```
Are there any reasons to avoid checking the permissions in this case?

**Comment by wombelix** [comment]
> @wombelix
> Why not to do it this way:
> 
> ```
> --- a/src/smdba/postgresqlgate.py
> +++ b/src/smdba/postgresqlgate.py
> @@ -767,6 +767,9 @@ class PgSQLGate(BaseGate):
>          if 'enable' in args.keys():
>              # Check destination only in case user is enabling the backup
>              if args.get('enable') == 'on':
> +                # If backup-dir is Symlink, use target instead
> +                while os.path.islink(args['backup-dir']):
> +                    args['backup-dir'] = os.readlink(args['backup-dir'])
>                  # Same owner?
>                  if os.lstat(args['backup-dir']).st_uid != os.lstat(self.config['pcnf_pg_data']).st_uid \
>                         or os.lstat(args['backup-dir']).st_gid != os.lstat(self.config['pcnf_pg_data']).st_gid:
> ```
> 
> Are there any reasons to avoid checking the permissions in this case?

@vzhestkov thanks for the suggestion, indeed focusing only on the symlink would be sufficient for my specific use case, I just thought if changes would be implemented, why not just covering another potential use case with minor additional effort :)

One thing I recognized today on my initial proposal, due to overwriting args['backup-dir'] with the symlink target path, that value also get written to the config /var/lib/pgsql/data/postgresql.conf (archive_command).
Ended up in a weird situation were smdba complained about different paths and that I have to purge my existing backup prior creating a new one, because backup-dir argument and path in the config differ.

I changed the code to keep the orignal value in a new var, run the permission check with args['backup-dir'] set to the symlink target and revert afterwards before _perform_enable_backup(**args) get executed. Will perform some tests and let you know the results.

**Comment by vzhestkov** [comment]
@wombelix yes, also missed this point by focusing only on this part.
@mcalmer do we need a parameter to skip permission checking? I'm not really sure that there should be any real use case for it.

**Comment by wombelix** [comment]
@vzhestkov so far the following seem to work as expected:
```
--- /usr/lib/python3.6/site-packages/smdba/postgresqlgate.py_org        2021-08-27 17:10:22.780052665 +0200
+++ /usr/lib/python3.6/site-packages/smdba/postgresqlgate.py    2021-08-31 13:49:25.212929097 +0200
@@ -764,6 +764,11 @@
         if 'enable' in args.keys():
             # Check destination only in case user is enabling the backup
             if args.get('enable') == 'on':
+                # If backup-dir is Symlink, use target instead
+                if os.path.islink(args['backup-dir']):
+                    # Save original value in temporary variable to re-assign after Permission Check
+                    args_backup_dir_orig = args['backup-dir']
+                    args['backup-dir'] = os.readlink(args_backup_dir_orig)
                 # Same owner?
                 if os.lstat(args['backup-dir']).st_uid != os.lstat(self.config['pcnf_pg_data']).st_uid \
                        or os.lstat(args['backup-dir']).st_gid != os.lstat(self.config['pcnf_pg_data']).st_gid:
@@ -774,6 +779,9 @@
                 if oct(os.lstat(args['backup-dir']).st_mode & 0o777) != oct(os.lstat(self.config['pcnf_pg_data']).st_mode & 0o777):
                     raise GateException("The \"%s\" directory must have the same permissions as \"%s\" directory."
                                         % (args['backup-dir'], self.config['pcnf_pg_data']))
+                # Avoid issues at a later point due to different paths by setting original value
+                if args_backup_dir_orig is not None:
+                    args['backup-dir'] = args_backup_dir_orig
             self._perform_enable_backups(**args)

         if 'source' in args.keys():
```

Out of interest, your proposal was using "while" instead "if", any specific reason? My understanding is that "backup-dir" will only contain a single path?
```
+                # If backup-dir is Symlink, use target instead
+                while os.path.islink(args['backup-dir']):
+                    args['backup-dir'] = os.readlink(args['backup-dir'])
```

**Comment by mcalmer** [comment]
> @mcalmer do we need a parameter to skip permission checking? I'm not really sure that there should be any real use case for it.

I really would like to keep the permission check. Backup will practically not work if the permissions are wrong but you can find the error only in the logs as it is a background process. And only a few people look into the logfiles.
Better to check the permissions on "enabling" the backup and fail directly with the right message. This will be seen by the user.

**Comment by vzhestkov** [comment]
@wombelix `while` is used to handle the cases when one symlink point to another symlink.

**Comment by wombelix** [comment]
> @wombelix `while` is used to handle the cases when one symlink point to another symlink.

Make sense, thank you very much :)

> I really would like to keep the permission check. Backup will practically not work if the permissions are wrong but you can find the error only in the logs as it is a background process. And only a few people look into the logfiles.
> Better to check the permissions on "enabling" the backup and fail directly with the right message. This will be seen by the user.

Thanks, I adjusted the Title accordingly, agree that supporting symlinks would already be sufficient to cover the use case I mentioned in my initial post and that ignoring the Owner/Permissions isn't necessary then.
